[package]
name = "barragekyi"
version = "0.1.0"
authors = ["Sean.W <imseean@gmail.com>"]

[dependencies]
hyper = "0.11"
tokio-core = "0.1"
futures = "0.1"
regex = "0.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
time = "0.1"
